name: deploy-app
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: WAS 인스턴스 접속 및 명령어 실행
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_SERVER_HOST }} # EC2 퍼블릭 IPv4 DNS
          username: ${{ secrets.SERVER_USERNAME }} # OS의 기본 사용자 이름
          key: ${{ secrets.EC2_KEY }} # EC2 pem
          script: |
            cd app
            ./deploy.sh
            cd hanbang/frontend
            pkill -f "node server.js"
            npm run build
            node server.js &
